[platformio]
default_envs = gateway
src_dir = mine_rescue_wokwi/gateway
build_dir = build

[env:gateway]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.3
